[package]
name = "cqf"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"

members = ["core", "bench", "cli", "providers"]

[workspace.package]
edition = "2021"
version = "0.14.0"
readme = "README.md"
license = "Apache-2.0"


[dependencies]

