[package]
name = "cli"
version = "0.1.0"
edition = "2021"
authors = ["liberxue@gmail.com"]
repository = "https://github.com/liberxue/cqf"
homepage = "https://github.com/liberxue"
[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
