[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
burn = { version = "0.13.2", features = ["train", "wgpu", "vision"] }
core = { path = "../core" }
plotters = "0.3.6"
