[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
path = "src/lib.rs"


rand = "0.8"
rand_distr = "0.4"


[[test]]
name = "core_tests"
path = "tests/black_scholes_tests.rs"
